### ISSUE TITLE
Request for Vuejs support

### ISSUE THREAD

**Issue by hansiemithun** [nikku/eslint-plugin-license-header#4]
Plugin is great !

I used your simple example of having header.js to use as a template and it did generate the file header in all the files. Unfortunately, even App.vue extension files got added with JS comment section, so this broke the application. So, Is there any idea to support Vue files or how to tweak to get this work for the Vue project?

Vue files expect HTML way of comments like

But there will be javascript files as well along with this with /* */. So, need to handle both scenarios.

And by any chance, can we have a pattern match also enabled inside header.js for copyright year to ignore 2020 strictly, some files will be 2019?

**Comment by nikku** [comment]
Please share a [codesandbox example](https://codesandbox.io), i.e. a vue application that shows your usage scenario.

Please also clearly document your expected behavior (in vue HTML files) as well as the current behavior.

That gives us a solid foundation to iterate your feature request. Maybe you can even contribute JS in HTML support (vue and svelte both need that).

**Comment by suterma** [comment]
I would like to have this reopened. The underlying issue is probably that strictly only javascript-type files are working. When using the --fix option, working with .vue SFC components, this plugin fails quite spectacularly, even worse than with  https://github.com/nikku/eslint-plugin-license-header/issues/13

@nikku Would you like me to elaborate here, or open an new issue?

**Comment by nikku** [comment]
@suterma The issue is closed for [a reason](https://github.com/nikku/eslint-plugin-license-header/issues/4#issuecomment-619525810).

If you want to contribute a test cases that reproduces the issue _then_ we may be able to look into a fix. I agree that JS in HTML support could be neat.

**Comment by suterma** [comment]
A fix would probably not be that simple, because, from a quick code inspection, you do actually work with code statements, not the first part of a file. Thus, for supporting multiple languages / source file types, you would need to implement or use a language parser/model, instead of just a quick search/insert at the beginning of the files(s).

**Comment by nikku** [comment]
> Thus, for supporting multiple languages / source file types, you would need to implement or use a language parser/model, instead of just a quick search/insert at the beginning of the files(s).

A great start could be a failing integration test case (using `vue` as an example).
